project:
  output-dir: docx
  render:
    - main.qmd

author: Carlos Ronchi, Cathrin Brisken

output-dir: docx

format:
  docx: default
  pdf: default
  html: default

self-contained: true

bibliography: references.bib
csl: csl/aacr.csl

execute: 
  echo: false
  warning: false
  error: false

title: > 
  Transcriptomic and machine learning based molecular landscape 
  provides a framework for better understanding estrogen receptor
  positive breast cancer