project:
    output-dir: docx
    render:
        - main.qmd

format:
  docx: default
  pdf: default
  html: default

self-contained: true

bibliography: references.bib
csl: csl/aacr.csl

execute: 
  echo: false
  warning: false
  error: false


title: > 
    Transcriptional signatures enable a personalized approach 
    for estrogen receptor positive breast cancer treatment

    
author: Carlos Ronchi, Cathrin Brisken
