project:
    output-dir: docx
    render:
        - main.qmd

format:
  docx: default
  pdf: default
  html: default

bibliography: references.bib
csl: csl/aacr.csl

execute: 
  echo: false
  warning: false
  error: false
