project:
    output-dir: docx
    render:
        - main.qmd

format:
  docx: default
  pdf: default
  html: default

bibliography: references.bib
csl: csl/aacr.csl

execute: 
  echo: false
  warning: false
  error: false


title: > 
    Molecular landscape: a new framework for 
    personalized medicine in Breast Cancer
    
author: Carlos Ronchi, Cathrin Brisken
