project:
  type: book
  output-dir: "../docs"

book:
  title: > 
    EMBER creates a unified space for 
    independent breast cancer transcriptomic 
    datasets enabling precision oncology.
  author: "Carlos Ronchi, Syed Haider, Cathrin Brisken"
  date: "2022.07.21"
  chapters:
    - index.qmd
    - chapters/intro.qmd
    - chapters/surv_analysis_estrogen.qmd
    - chapters/pca_merging.qmd
    - chapters/validation.qmd
    - chapters/scoring.qmd
    - chapters/risk_score.qmd
    - chapters/expanding_ember.qmd
    - chapters/trying.qmd
    - chapters/revision.qmd
    - chapters/discussion.qmd
    - chapters/references.qmd
  page-footer: 
    right: 
      - icon: github
        href: https://github.com/chronchi
      - icon: twitter 
        href: https://twitter.com/chronchi
  repo-url: https://github.com/chronchi/molecular_landscape
  repo-actions: [issue]
  sharing: [twitter]

bibliography: chapters/references.bib

execute: 
  eval: true
  warning: false
  echo: false
  error: false
  freeze: auto # re-render when source code changes

format:
  html:
    theme: cosmo
    code-summary: "Show the code"
    code-tools: true
    reference-location: margin
  pdf:
    documentclass: scrreprt
  docx:
    toc: true
    number-sections: true
    highlight-style: github
