project:
  type: book
  output-dir: "../results/book"

book:
  title: > 
    Molecular landscape: a new framework for 
    personalized medicine in Breast Cancer.
  author: "Carlos Ronchi, Cathrin Brisken"
  date: "2022.07.21"
  chapters:
    - index.qmd
    - intro.qmd
    - surv_analysis_estrogen.qmd
    - pca_merging.qmd
    - validation.qmd
    - scoring.qmd
    - risk_score.qmd
    - trying.qmd
    - discussion.qmd
    - references.qmd
  page-footer: 
    right: 
      - icon: github
        href: https://github.com/chronchi
      - icon: twitter 
        href: https://twitter.com/chronchi
  repo-url: https://github.com/chronchi/molecular_landscape
  repo-actions: [issue]
  sharing: [twitter]

bibliography: references.bib

execute: 
  eval: true
  warning: false
  echo: false
  error: false
  freeze: auto # re-render when source code changes

format:
  html:
    theme: cosmo
    code-summary: "Show the code"
    code-tools: true
    reference-location: margin
  pdf:
    documentclass: scrreprt
  docx:
    toc: true
    number-sections: true
    highlight-style: github
